name: sea_catering
description: "A Flutter Catering project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^3.3.1
  url_launcher: ^6.1.12
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #Cached images
  cached_network_image: ^3.0.0

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.9.0
  google_sign_in: ^6.1.6

  #Supabase
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  image: assets/images/logo_catering.png
  image_dark: assets/images/logo_catering.png
  background_image: assets/images/background.png
  background_image_dark: assets/images/background.png

  android_12:
    image: assets/images/logo_catering.png
    image_dark: assets/images/logo_catering.png
    background_image: assets/images/background.png
    background_image_dark: assets/images/background.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/background.png
    - assets/images/logo_catering.png
    - assets/images/pfp.jpg
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/
    - assets/images/banner/indonesia.png
    - assets/images/banner/
    - assets/profilepicture/
    - assets/paymentmethods/
    - assets/images/
    - assets/images/weight_loss/
    - assets/images/foodcarousel/
    - assets/images/experiencecarousel/
    - assets/images/foods/
    - assets/images/drinks/
    - assets/images/veggies/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

