// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbadnFXaSYECGcCkCiGMRt1TjwkIRcq0s',
    appId: '1:231805258566:web:63433fcdce5dc2613db347',
    messagingSenderId: '231805258566',
    projectId: 'agribridge4',
    authDomain: 'agribridge4.firebaseapp.com',
    storageBucket: 'agribridge4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Yl_SXQkH5hqAgVggUntQc-g1SnfsAHE',
    appId: '1:231805258566:android:315963677a6ae4323db347',
    messagingSenderId: '231805258566',
    projectId: 'agribridge4',
    storageBucket: 'agribridge4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdMvBsFUNtTEFYJxRtWwxBUeMb9uLp4To',
    appId: '1:231805258566:ios:5164f45731cb57ae3db347',
    messagingSenderId: '231805258566',
    projectId: 'agribridge4',
    storageBucket: 'agribridge4.firebasestorage.app',
    iosClientId: '231805258566-k50ec6up9rt9vl1jpv7ul70eq9rcjfb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appppppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbadnFXaSYECGcCkCiGMRt1TjwkIRcq0s',
    appId: '1:231805258566:web:3b5d0fb48b145f683db347',
    messagingSenderId: '231805258566',
    projectId: 'agribridge4',
    authDomain: 'agribridge4.firebaseapp.com',
    storageBucket: 'agribridge4.firebasestorage.app',
  );

}