// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWUrwjmEakg8w7T8_xf-nULcxHNT0We_Y',
    appId: '1:404906785626:web:c25ae1b089395e347a5163',
    messagingSenderId: '404906785626',
    projectId: 'sea-catering-5fed1',
    authDomain: 'sea-catering-5fed1.firebaseapp.com',
    storageBucket: 'sea-catering-5fed1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3fS11mYXDfWfc4h2MAlPsM0Oah19UwXU',
    appId: '1:404906785626:android:f709895b4b78620e7a5163',
    messagingSenderId: '404906785626',
    projectId: 'sea-catering-5fed1',
    storageBucket: 'sea-catering-5fed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZlPH48Lw6cQFltR-zj1eZgnLLd2iaFU',
    appId: '1:404906785626:ios:6c057622efc28d7b7a5163',
    messagingSenderId: '404906785626',
    projectId: 'sea-catering-5fed1',
    storageBucket: 'sea-catering-5fed1.firebasestorage.app',
    androidClientId: '404906785626-1vknnlri8nr1ducvequmb6ibhqm8cp8e.apps.googleusercontent.com',
    iosClientId: '404906785626-4gko4a0p02pog7ha20jni758846lcaik.apps.googleusercontent.com',
    iosBundleId: 'com.example.appppppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWUrwjmEakg8w7T8_xf-nULcxHNT0We_Y',
    appId: '1:404906785626:web:62bcc4fcf6b6d4607a5163',
    messagingSenderId: '404906785626',
    projectId: 'sea-catering-5fed1',
    authDomain: 'sea-catering-5fed1.firebaseapp.com',
    storageBucket: 'sea-catering-5fed1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZlPH48Lw6cQFltR-zj1eZgnLLd2iaFU',
    appId: '1:404906785626:ios:6c057622efc28d7b7a5163',
    messagingSenderId: '404906785626',
    projectId: 'sea-catering-5fed1',
    storageBucket: 'sea-catering-5fed1.firebasestorage.app',
    androidClientId: '404906785626-1vknnlri8nr1ducvequmb6ibhqm8cp8e.apps.googleusercontent.com',
    iosClientId: '404906785626-4gko4a0p02pog7ha20jni758846lcaik.apps.googleusercontent.com',
    iosBundleId: 'com.example.appppppp',
  );

}